#!/usr/bin/env bash

set -e

enable_systemd_services() {
    systemctl --user daemon-reload
    systemctl --user enable picontrol.service
    systemctl --user start picontrol.service
}

testington() {
    false
}

main() {
    #enable_systemd_services
    testington

    return 0
}

main
exit $?
