name: Lint code
env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}
on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed
jobs:
  lint:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Lint code
        run: |
          find . -type f \( -iname \*.c -o -iname \*.h \) | xargs clang-format -style=google --dry-run --Werror
